 1. Import the necessary libraries

In [5]:
import pandas as pd

2. This is the data given as a dictionary
3. Create a dataframe and assign it to a variable called army.

In [55]:
army = pd.DataFrame({'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']})
army

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
4,Dragoons,1st,43,4,1592,73,2,0,3,Maine
5,Dragoons,1st,234,7,1006,37,1,1,4,Iowa
6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
7,Dragoons,2nd,62,3,849,48,3,1,31,Washington
8,Scouts,1st,62,4,973,48,2,0,2,Oregon
9,Scouts,1st,73,7,1005,435,1,0,3,Wyoming
10,Scouts,2nd,37,8,1099,63,2,1,2,Louisana
11,Scouts,2nd,35,9,1523,345,3,1,3,Georgia

4. Set the 'origin' colum as the index of the dataframe

In [57]:
army.set_index('origin',inplace=True)
army

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

5. Print only the column veterans

In [11]:
army.veterans

0       1
1       5
2      62
3      26
4      73
5      37
6     949
7      48
8      48
9     435
10     63
11    345
Name: veterans, dtype: int64

6. Print the columns 'veterans' and 'deaths'

In [12]:
army[[ 'veterans','deaths']]

    veterans  deaths
0          1     523
1          5      52
2         62      25
3         26     616
4         73      43
5         37     234
6        949     523
7         48      62
8         48      62
9        435      73
10        63      37
11       345      35

7. Print the name of all the columns.

In [13]:
army.columns

Index(['regiment', 'company', 'deaths', 'battles', 'size', 'veterans',
       'readiness', 'armored', 'deserters', 'origin'],
      dtype='object')

 8. Select the 'deaths', 'size' and 'deserters' columns from Maine and Alaska

In [20]:
army.loc[['Maine','Alaska'],['deaths','size','deserters']]

        deaths  size  deserters
origin
Maine       43  1592          3
Alaska     523   987         24

9. Select the rows 3 to 7 and the columns 3 to 6

In [61]:
army.iloc[2:7,2:6]

         deaths  battles  size  veterans
origin
Texas        25        2  1099        62
Florida     616        2  1400        26
Maine        43        4  1592        73
Iowa        234        7  1006        37
Alaska      523        8   987       949

10. Select every row after the fourth row and all columns

In [30]:
army.iloc[4:,:]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

11. Select every row up to the 4th row and all columns

In [31]:
army.iloc[:4,:]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2

12. Select the 3rd column up to the 7th column

In [62]:
army.iloc[:,2:7]

            deaths  battles  size  veterans  readiness
origin
Arizona        523        5  1045         1          1
California      52       42   957         5          2
Texas           25        2  1099        62          3
Florida        616        2  1400        26          3
Maine           43        4  1592        73          2
Iowa           234        7  1006        37          1
Alaska         523        8   987       949          2
Washington      62        3   849        48          3
Oregon          62        4   973        48          2
Wyoming         73        7  1005       435          1
Louisana        37        8  1099        63          2
Georgia         35        9  1523       345          3

13. Select rows where df.deaths is greater than 50

In [34]:
army.loc[army.deaths>50]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3

14. Select rows where df.deaths is greater than 500 or less than 50

In [39]:
army.loc[(army.deaths>500)|(army.deaths<50)]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

15. Select all the regiments not named "Dragoons"

In [41]:
army.loc[army.regiment!='Dragoons']

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

16. Select the rows called Texas and Arizona

In [42]:
army.loc[['Texas' ,'Arizona'],:]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4

17. Select the third cell in the row named Arizona

In [64]:
value=army.loc[['Arizona']].iloc[:,2]
value

origin
Arizona    523
Name: deaths, dtype: int64

18. Select the third cell down in the column named deaths

In [68]:
army.loc[:,['deaths']].iloc[2]

deaths    25
Name: Texas, dtype: int64